[package]
name = "advent-of-code-2019"
version = "0.1.0"
authors = ["Byron Wasti <byron.wasti@gmail.com>"]
edition = "2018"

[dependencies]
permutohedron = "0.2.4"
termion = "1.5.4"
log = "0.4.8"
fern = "0.5.9"
chrono = "0.4.10"
